// src/components/PaperPage.jsx
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { getPaperDetails } from "../api/paperApi";
import axios from "axios";
import AnalysisPanel from "../components/AnalysisPanel"; // Make sure to create this component

export default function PaperPage() {
  const { paperId } = useParams();
  const [paper, setPaper] = useState(null);
  const [pdfText, setPdfText] = useState("");
  const [loading, setLoading] = useState({
    paper: true,
    pdfText: false
  });
  const [error, setError] = useState(null);
  const [extractionError, setExtractionError] = useState(null);
  const [showAnalysis, setShowAnalysis] = useState(false);

  // Fetch paper details
  useEffect(() => {
    async function loadPaperDetails() {
      try {
        const data = await getPaperDetails(paperId);
        setPaper(data);
        setLoading(prev => ({ ...prev, paper: false }));
      } catch (err) {
        setError("Failed to load paper details");
        setLoading(prev => ({ ...prev, paper: false }));
      }
    }

    loadPaperDetails();
  }, [paperId]);
  
  // Function to fetch PDF text from Flask backend
  async function fetchPdfText(url) {
    try {
      setLoading(prev => ({ ...prev, pdfText: true }));
      setExtractionError(null);
      
      // Call your Flask API to extract text
      const response = await axios.post("http://localhost:3000/extract-text", {
        url: url
      });
      
      setPdfText(response.data.text);
      // Auto-show analysis panel when text is extracted
      setShowAnalysis(true);
    } catch (err) {
      console.error("Failed to extract PDF text:", err);
      setExtractionError(
        err.response?.data?.error || 
        "Failed to extract text from the PDF. The server might be down or the PDF is not accessible."
      );
    } finally {
      setLoading(prev => ({ ...prev, pdfText: false }));
    }
  }

  // Placeholder summary
  const placeholderSummary = "This is a placeholder summary of the paper. In the future, this will be generated by an AI model based on the paper's content.";

  if (loading.paper) return <div>Loading paper details...</div>;
  if (error) return <div className="error-message">{error}</div>;
  if (!paper) return <div>Paper not found</div>;

  return (
    <div className="paper-details">
      <h1>{paper.title}</h1>
      
      <div className="paper-metadata">
        <p>
          <strong>Authors:</strong>{" "}
          {paper.authors?.length
            ? paper.authors.map((a, index) => (
                <span key={index}>{a.name || 'Unknown'}{index < paper.authors.length - 1 ? ', ' : ''}</span>
              ))
            : 'No authors available'}
        </p>
        
        <p><strong>Year:</strong> {paper.year}</p>
        {paper.venue && <p><strong>Venue:</strong> {paper.venue}</p>}
        
        {paper.fieldsOfStudy?.length > 0 && (
          <p>
            <strong>Fields of Study:</strong>{" "}
            {paper.fieldsOfStudy.join(", ")}
          </p>
        )}
      </div>

      <div className="paper-content">
        <h2>Abstract</h2>
        <p>{paper.abstract || "No abstract available"}</p>
        
        <h2>AI Summary</h2>
        <div className="ai-summary">
          <p>{paper.tldr?.text || placeholderSummary}</p>
        </div>
        
        {/* Paper Content Section */}
        <div className="content-section">
          <h2>Paper Content</h2>
          {loading.pdfText ? (
            <div className="loading-text">Extracting text from PDF...</div>
          ) : pdfText ? (
            <div className="pdf-text">
              {pdfText.split('\n\n').map((paragraph, index) => (
                paragraph.trim() ? (
                  <p key={index}>{paragraph}</p>
                ) : null
              ))}
            </div>
          ) : (
            <div>
              {paper.pdfUrl ? (
                <p>Click "Extract Paper Text" to view the full content.</p>
              ) : (
                <p>No PDF available for this paper.</p>
              )}
            </div>
          )}
          
          {extractionError && (
            <div className="error-message">{extractionError}</div>
          )}
          
          {paper.pdfUrl && !pdfText && !loading.pdfText && (
            <button 
              onClick={() => fetchPdfText(paper.pdfUrl)}
              className="action-button"
            >
              Extract Paper Text
            </button>
          )}
        </div>
        
        {/* AI Analysis Panel */}
        {pdfText && showAnalysis && (
          <AnalysisPanel pdfText={pdfText} />
        )}
      </div>
      
      <div className="paper-actions">
        {paper.url && (
          <a 
            href={paper.url} 
            target="_blank" 
            rel="noopener noreferrer"
            className="action-button"
          >
            Read on arXiv
          </a>
        )}

        {paper.pdfUrl && (
          <>
            <a 
              href={paper.pdfUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="action-button pdf-button"
            >
              Download PDF
            </a>
            
            {pdfText && !showAnalysis && (
              <button 
                onClick={() => setShowAnalysis(true)}
                className="action-button analyze-button"
              >
                Show AI Analysis
              </button>
            )}
          </>
        )}
      </div>
    </div>
  );
}
